2019-12-16 14:28:05 WARN  ConnectionUtil:31 - Unable to obtain connection to database
java.sql.SQLException: No suitable driver found for jdbc:postgresql://localhost:5432/
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.revature.util.ConnectionUtil.getConnection(ConnectionUtil.java:29)
	at com.revature.repositories.EmployeeDAOImpl.findAll(EmployeeDAOImpl.java:28)
	at com.revature.services.EmployeeService.findAll(EmployeeService.java:23)
	at com.revature.Driver.main(Driver.java:19)
2019-12-16 15:00:24 WARN  ConnectionUtil:31 - Unable to obtain connection to database
java.sql.SQLException: No suitable driver found for jdbc:postgresql://localhost:51341/
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.revature.util.ConnectionUtil.getConnection(ConnectionUtil.java:29)
	at com.revature.repositories.EmployeeDAOImpl.findAll(EmployeeDAOImpl.java:28)
	at com.revature.services.EmployeeService.findAll(EmployeeService.java:23)
	at com.revature.Driver.main(Driver.java:19)
2019-12-16 15:06:26 WARN  ConnectionUtil:31 - Unable to obtain connection to database
java.sql.SQLException: No suitable driver found for jdbc:postgresql://localhost:51341/postgres
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.revature.util.ConnectionUtil.getConnection(ConnectionUtil.java:29)
	at com.revature.repositories.EmployeeDAOImpl.findAll(EmployeeDAOImpl.java:28)
	at com.revature.services.EmployeeService.findAll(EmployeeService.java:23)
	at com.revature.Driver.main(Driver.java:19)
2019-12-16 15:06:26 WARN  EmployeeDAOImpl:60 - Connection to db not created
java.lang.NullPointerException
	at com.revature.repositories.EmployeeDAOImpl.findAll(EmployeeDAOImpl.java:32)
	at com.revature.services.EmployeeService.findAll(EmployeeService.java:23)
	at com.revature.Driver.main(Driver.java:19)
2019-12-16 15:10:41 WARN  ConnectionUtil:31 - Unable to obtain connection to database
java.sql.SQLException: No suitable driver found for jdbc:postgresql://localhost:51341/postgres
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.revature.util.ConnectionUtil.getConnection(ConnectionUtil.java:29)
	at com.revature.repositories.EmployeeDAOImpl.findAll(EmployeeDAOImpl.java:28)
	at com.revature.services.EmployeeService.findAll(EmployeeService.java:23)
	at com.revature.Driver.main(Driver.java:19)
2019-12-16 15:10:41 WARN  EmployeeDAOImpl:60 - Connection to db not created
java.lang.NullPointerException
	at com.revature.repositories.EmployeeDAOImpl.findAll(EmployeeDAOImpl.java:32)
	at com.revature.services.EmployeeService.findAll(EmployeeService.java:23)
	at com.revature.Driver.main(Driver.java:19)
2019-12-16 15:11:08 WARN  ConnectionUtil:31 - Unable to obtain connection to database
java.sql.SQLException: No suitable driver found for jdbc:postgresql://127.0.0.1:51341/postgres
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.revature.util.ConnectionUtil.getConnection(ConnectionUtil.java:29)
	at com.revature.repositories.EmployeeDAOImpl.findAll(EmployeeDAOImpl.java:28)
	at com.revature.services.EmployeeService.findAll(EmployeeService.java:23)
	at com.revature.Driver.main(Driver.java:19)
2019-12-16 15:11:08 WARN  EmployeeDAOImpl:60 - Connection to db not created
java.lang.NullPointerException
	at com.revature.repositories.EmployeeDAOImpl.findAll(EmployeeDAOImpl.java:32)
	at com.revature.services.EmployeeService.findAll(EmployeeService.java:23)
	at com.revature.Driver.main(Driver.java:19)
2019-12-16 15:17:46 WARN  ConnectionUtil:31 - Unable to obtain connection to database
java.sql.SQLException: No suitable driver found for jdbc:postgresql://localhost/postgres
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.revature.util.ConnectionUtil.getConnection(ConnectionUtil.java:29)
	at com.revature.repositories.EmployeeDAOImpl.findAll(EmployeeDAOImpl.java:28)
	at com.revature.services.EmployeeService.findAll(EmployeeService.java:23)
	at com.revature.Driver.main(Driver.java:19)
2019-12-16 15:17:46 WARN  EmployeeDAOImpl:60 - Connection to db not created
java.lang.NullPointerException
	at com.revature.repositories.EmployeeDAOImpl.findAll(EmployeeDAOImpl.java:32)
	at com.revature.services.EmployeeService.findAll(EmployeeService.java:23)
	at com.revature.Driver.main(Driver.java:19)
2019-12-16 15:18:06 WARN  ConnectionUtil:31 - Unable to obtain connection to database
java.sql.SQLException: No suitable driver found for jdbc:postgresql:postgres
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.revature.util.ConnectionUtil.getConnection(ConnectionUtil.java:29)
	at com.revature.repositories.EmployeeDAOImpl.findAll(EmployeeDAOImpl.java:28)
	at com.revature.services.EmployeeService.findAll(EmployeeService.java:23)
	at com.revature.Driver.main(Driver.java:19)
2019-12-16 15:18:06 WARN  EmployeeDAOImpl:60 - Connection to db not created
java.lang.NullPointerException
	at com.revature.repositories.EmployeeDAOImpl.findAll(EmployeeDAOImpl.java:32)
	at com.revature.services.EmployeeService.findAll(EmployeeService.java:23)
	at com.revature.Driver.main(Driver.java:19)
2019-12-16 15:19:31 WARN  ConnectionUtil:31 - Unable to obtain connection to database
java.sql.SQLException: No suitable driver found for jdbc:postgresql://localhost:5432/postgres
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.revature.util.ConnectionUtil.getConnection(ConnectionUtil.java:29)
	at com.revature.repositories.EmployeeDAOImpl.findAll(EmployeeDAOImpl.java:28)
	at com.revature.services.EmployeeService.findAll(EmployeeService.java:23)
	at com.revature.Driver.main(Driver.java:19)
2019-12-16 15:19:31 WARN  EmployeeDAOImpl:60 - Connection to db not created
java.lang.NullPointerException
	at com.revature.repositories.EmployeeDAOImpl.findAll(EmployeeDAOImpl.java:32)
	at com.revature.services.EmployeeService.findAll(EmployeeService.java:23)
	at com.revature.Driver.main(Driver.java:19)
2019-12-16 15:24:54 WARN  ConnectionUtil:31 - Unable to obtain connection to database
java.sql.SQLException: No suitable driver found for jdbc:postgresql://localhost:5432/postgres
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.revature.util.ConnectionUtil.getConnection(ConnectionUtil.java:29)
	at com.revature.repositories.EmployeeDAOImpl.findAll(EmployeeDAOImpl.java:28)
	at com.revature.services.EmployeeService.findAll(EmployeeService.java:23)
	at com.revature.Driver.main(Driver.java:19)
2019-12-16 15:24:54 WARN  EmployeeDAOImpl:60 - Connection to db not created
java.lang.NullPointerException
	at com.revature.repositories.EmployeeDAOImpl.findAll(EmployeeDAOImpl.java:32)
	at com.revature.services.EmployeeService.findAll(EmployeeService.java:23)
	at com.revature.Driver.main(Driver.java:19)
2019-12-16 15:31:57 WARN  ConnectionUtil:31 - Unable to obtain connection to database
java.sql.SQLException: No suitable driver found for jdbc:postgresql://localhost/postgres
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.revature.util.ConnectionUtil.getConnection(ConnectionUtil.java:29)
	at com.revature.repositories.EmployeeDAOImpl.findAll(EmployeeDAOImpl.java:28)
	at com.revature.services.EmployeeService.findAll(EmployeeService.java:23)
	at com.revature.Driver.main(Driver.java:19)
2019-12-16 15:31:57 WARN  EmployeeDAOImpl:60 - Connection to db not created
java.lang.NullPointerException
	at com.revature.repositories.EmployeeDAOImpl.findAll(EmployeeDAOImpl.java:32)
	at com.revature.services.EmployeeService.findAll(EmployeeService.java:23)
	at com.revature.Driver.main(Driver.java:19)
2019-12-16 15:32:07 WARN  ConnectionUtil:31 - Unable to obtain connection to database
java.sql.SQLException: No suitable driver found for jdbc:postgresql://localhost:5432/postgres
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.revature.util.ConnectionUtil.getConnection(ConnectionUtil.java:29)
	at com.revature.repositories.EmployeeDAOImpl.findAll(EmployeeDAOImpl.java:28)
	at com.revature.services.EmployeeService.findAll(EmployeeService.java:23)
	at com.revature.Driver.main(Driver.java:19)
2019-12-16 15:32:07 WARN  EmployeeDAOImpl:60 - Connection to db not created
java.lang.NullPointerException
	at com.revature.repositories.EmployeeDAOImpl.findAll(EmployeeDAOImpl.java:32)
	at com.revature.services.EmployeeService.findAll(EmployeeService.java:23)
	at com.revature.Driver.main(Driver.java:19)
2019-12-16 15:46:47 WARN  ConnectionUtil:31 - Unable to obtain connection to database
java.sql.SQLException: No suitable driver found for jdbc:postgresql://localhost:5432/postgres
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.revature.util.ConnectionUtil.getConnection(ConnectionUtil.java:29)
	at com.revature.repositories.EmployeeDAOImpl.findAll(EmployeeDAOImpl.java:28)
	at com.revature.services.EmployeeService.findAll(EmployeeService.java:23)
	at com.revature.Driver.main(Driver.java:19)
2019-12-16 15:46:47 WARN  EmployeeDAOImpl:60 - Connection to db not created
java.lang.NullPointerException
	at com.revature.repositories.EmployeeDAOImpl.findAll(EmployeeDAOImpl.java:32)
	at com.revature.services.EmployeeService.findAll(EmployeeService.java:23)
	at com.revature.Driver.main(Driver.java:19)
2019-12-17 10:29:50 WARN  CustomerDAOImpl:57 - Unable to add customer to DB
org.postgresql.util.PSQLException: ERROR: column "elijah" does not exist
  Position: 37
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:309)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:295)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:272)
	at org.postgresql.jdbc.PgStatement.executeUpdate(PgStatement.java:246)
	at com.revature.repositories.CustomerDAOImpl.insert(CustomerDAOImpl.java:55)
	at com.revature.services.CustomerService.insert(CustomerService.java:24)
	at com.revature.Driver.createAccount(Driver.java:71)
	at com.revature.Driver.openMenu(Driver.java:48)
	at com.revature.Driver.main(Driver.java:28)
2019-12-17 19:42:26 WARN  CustomerDAOImpl:82 - User or password not in db
org.postgresql.util.PSQLException: ERROR: missing FROM-clause entry for table "elijah"
  Position: 43
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:309)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:295)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:272)
	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:225)
	at com.revature.repositories.CustomerDAOImpl.findByLogin(CustomerDAOImpl.java:76)
	at com.revature.services.CustomerService.findByLogin(CustomerService.java:28)
	at com.revature.services.LoginService.login(LoginService.java:10)
	at com.revature.Driver.login(Driver.java:84)
	at com.revature.Driver.openMenu(Driver.java:52)
	at com.revature.Driver.main(Driver.java:30)
2019-12-17 19:42:26 WARN  EmployeeDAOImpl:125 - User or password does not exist
org.postgresql.util.PSQLException: ERROR: missing FROM-clause entry for table "elijah"
  Position: 43
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:309)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:295)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:272)
	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:225)
	at com.revature.repositories.EmployeeDAOImpl.findByLogin(EmployeeDAOImpl.java:117)
	at com.revature.services.EmployeeService.findByLogin(EmployeeService.java:27)
	at com.revature.services.LoginService.login(LoginService.java:10)
	at com.revature.Driver.login(Driver.java:84)
	at com.revature.Driver.openMenu(Driver.java:52)
	at com.revature.Driver.main(Driver.java:30)
2019-12-17 19:47:40 WARN  CustomerDAOImpl:82 - User or password not in db
org.postgresql.util.PSQLException: ResultSet not positioned properly, perhaps you need to call next.
	at org.postgresql.jdbc.PgResultSet.checkResultSet(PgResultSet.java:2786)
	at org.postgresql.jdbc.PgResultSet.getString(PgResultSet.java:1887)
	at org.postgresql.jdbc.PgResultSet.getString(PgResultSet.java:2480)
	at com.revature.repositories.CustomerDAOImpl.findByLogin(CustomerDAOImpl.java:77)
	at com.revature.services.CustomerService.findByLogin(CustomerService.java:28)
	at com.revature.services.LoginService.login(LoginService.java:10)
	at com.revature.Driver.login(Driver.java:84)
	at com.revature.Driver.openMenu(Driver.java:52)
	at com.revature.Driver.main(Driver.java:30)
2019-12-17 19:47:40 WARN  EmployeeDAOImpl:125 - User or password does not exist
org.postgresql.util.PSQLException: ResultSet not positioned properly, perhaps you need to call next.
	at org.postgresql.jdbc.PgResultSet.checkResultSet(PgResultSet.java:2786)
	at org.postgresql.jdbc.PgResultSet.getInt(PgResultSet.java:2046)
	at org.postgresql.jdbc.PgResultSet.getInt(PgResultSet.java:2498)
	at com.revature.repositories.EmployeeDAOImpl.findByLogin(EmployeeDAOImpl.java:118)
	at com.revature.services.EmployeeService.findByLogin(EmployeeService.java:27)
	at com.revature.services.LoginService.login(LoginService.java:10)
	at com.revature.Driver.login(Driver.java:84)
	at com.revature.Driver.openMenu(Driver.java:52)
	at com.revature.Driver.main(Driver.java:30)
2019-12-17 19:48:07 INFO  Driver:75 - Account created
2019-12-17 19:48:23 WARN  CustomerDAOImpl:82 - User or password not in db
org.postgresql.util.PSQLException: ResultSet not positioned properly, perhaps you need to call next.
	at org.postgresql.jdbc.PgResultSet.checkResultSet(PgResultSet.java:2786)
	at org.postgresql.jdbc.PgResultSet.getString(PgResultSet.java:1887)
	at org.postgresql.jdbc.PgResultSet.getString(PgResultSet.java:2480)
	at com.revature.repositories.CustomerDAOImpl.findByLogin(CustomerDAOImpl.java:77)
	at com.revature.services.CustomerService.findByLogin(CustomerService.java:28)
	at com.revature.services.LoginService.login(LoginService.java:10)
	at com.revature.Driver.login(Driver.java:84)
	at com.revature.Driver.openMenu(Driver.java:52)
	at com.revature.Driver.main(Driver.java:30)
2019-12-17 19:48:23 WARN  EmployeeDAOImpl:125 - User or password does not exist
org.postgresql.util.PSQLException: ResultSet not positioned properly, perhaps you need to call next.
	at org.postgresql.jdbc.PgResultSet.checkResultSet(PgResultSet.java:2786)
	at org.postgresql.jdbc.PgResultSet.getInt(PgResultSet.java:2046)
	at org.postgresql.jdbc.PgResultSet.getInt(PgResultSet.java:2498)
	at com.revature.repositories.EmployeeDAOImpl.findByLogin(EmployeeDAOImpl.java:118)
	at com.revature.services.EmployeeService.findByLogin(EmployeeService.java:27)
	at com.revature.services.LoginService.login(LoginService.java:10)
	at com.revature.Driver.login(Driver.java:84)
	at com.revature.Driver.openMenu(Driver.java:52)
	at com.revature.Driver.main(Driver.java:30)
2019-12-17 19:51:02 WARN  CustomerDAOImpl:82 - User or password not in db
org.postgresql.util.PSQLException: ResultSet not positioned properly, perhaps you need to call next.
	at org.postgresql.jdbc.PgResultSet.checkResultSet(PgResultSet.java:2786)
	at org.postgresql.jdbc.PgResultSet.getString(PgResultSet.java:1887)
	at org.postgresql.jdbc.PgResultSet.getString(PgResultSet.java:2480)
	at com.revature.repositories.CustomerDAOImpl.findByLogin(CustomerDAOImpl.java:77)
	at com.revature.services.CustomerService.findByLogin(CustomerService.java:28)
	at com.revature.services.LoginService.login(LoginService.java:10)
	at com.revature.Driver.login(Driver.java:84)
	at com.revature.Driver.openMenu(Driver.java:52)
	at com.revature.Driver.main(Driver.java:30)
2019-12-17 19:51:03 WARN  EmployeeDAOImpl:125 - User or password does not exist
org.postgresql.util.PSQLException: ResultSet not positioned properly, perhaps you need to call next.
	at org.postgresql.jdbc.PgResultSet.checkResultSet(PgResultSet.java:2786)
	at org.postgresql.jdbc.PgResultSet.getInt(PgResultSet.java:2046)
	at org.postgresql.jdbc.PgResultSet.getInt(PgResultSet.java:2498)
	at com.revature.repositories.EmployeeDAOImpl.findByLogin(EmployeeDAOImpl.java:118)
	at com.revature.services.EmployeeService.findByLogin(EmployeeService.java:27)
	at com.revature.services.LoginService.login(LoginService.java:10)
	at com.revature.Driver.login(Driver.java:84)
	at com.revature.Driver.openMenu(Driver.java:52)
	at com.revature.Driver.main(Driver.java:30)
2019-12-17 19:56:48 WARN  EmployeeDAOImpl:125 - User or password does not exist
org.postgresql.util.PSQLException: ResultSet not positioned properly, perhaps you need to call next.
	at org.postgresql.jdbc.PgResultSet.checkResultSet(PgResultSet.java:2786)
	at org.postgresql.jdbc.PgResultSet.getInt(PgResultSet.java:2046)
	at org.postgresql.jdbc.PgResultSet.getInt(PgResultSet.java:2498)
	at com.revature.repositories.EmployeeDAOImpl.findByLogin(EmployeeDAOImpl.java:118)
	at com.revature.services.EmployeeService.login(EmployeeService.java:32)
	at com.revature.Driver.login(Driver.java:86)
	at com.revature.Driver.openMenu(Driver.java:52)
	at com.revature.Driver.main(Driver.java:30)
2019-12-17 19:56:48 INFO  Driver:92 - Customer has logged in
